ERROR - 2025-06-10 01:27:15 --> Error connecting to the database: mysqli_sql_exception: 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 in C:\xampp\htdocs\ltutor\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\ltutor\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('34.172.45.196', 'ltedu_dev', Object(SensitiveParameterValue), 'ltrust', 3306, '', 0)
#1 C:\xampp\htdocs\ltutor\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ltutor\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ltutor\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ltutor\system\Model.php(213): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ltutor\system\BaseModel.php(613): CodeIgniter\Model->doFind(false, NULL)
#6 C:\xampp\htdocs\ltutor\app\Controllers\User.php(25): CodeIgniter\BaseModel->find()
#7 C:\xampp\htdocs\ltutor\system\CodeIgniter.php(933): App\Controllers\User->login()
#8 C:\xampp\htdocs\ltutor\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#9 C:\xampp\htdocs\ltutor\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\ltutor\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\ltutor\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\ltutor\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 in C:\xampp\htdocs\ltutor\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\ltutor\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ltutor\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ltutor\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ltutor\system\Model.php(213): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ltutor\system\BaseModel.php(613): CodeIgniter\Model->doFind(false, NULL)
#5 C:\xampp\htdocs\ltutor\app\Controllers\User.php(25): CodeIgniter\BaseModel->find()
#6 C:\xampp\htdocs\ltutor\system\CodeIgniter.php(933): App\Controllers\User->login()
#7 C:\xampp\htdocs\ltutor\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\ltutor\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ltutor\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\ltutor\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\ltutor\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-06-10 01:27:15 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。
[Method: GET, Route: login]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user_users`
WHERE `email` = :email:', [...], false)
 3 SYSTEMPATH\Model.php(213): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(613): CodeIgniter\Model->doFind(false, null)
 5 APPPATH\Controllers\User.php(25): CodeIgniter\BaseModel->find()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\User->login()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-10 03:08:05 --> ErrorException: Undefined property: Firebase\JWT\JWT::$tokenTTL
[Method: GET, Route: login]
in APPPATH\Libraries\JwtLibrary.php on line 24.
 1 APPPATH\Libraries\JwtLibrary.php(24): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: Firebase\\JWT\\JWT::$tokenTTL', 'C:\\xampp\\htdocs\\ltutor\\app\\Libraries\\JwtLibrary.php', 24)
 2 APPPATH\Controllers\User.php(37): App\Libraries\JwtLibrary->generateToken([...])
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\User->login()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-10 03:58:50 --> ErrorException: Cannot declare class App\Libraries\JwtLibrary, because the name is already in use
[Method: GET, Route: login]
in APPPATH\Libraries\RedisLibrary.php on line 9.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2025-06-10 06:43:56 --> Predis\Response\ServerException: ERR syntax error
[Method: GET, Route: login]
in VENDORPATH\predis\predis\src\Client.php on line 422.
 1 VENDORPATH\predis\predis\src\Client.php(387): Predis\Client->onErrorResponse(Object(Predis\Command\Redis\SET), Object(Predis\Response\Error))
 2 VENDORPATH\predis\predis\src\Client.php(336): Predis\Client->executeCommand(Object(Predis\Command\Redis\SET))
 3 APPPATH\Controllers\User.php(52): Predis\Client->__call('set', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\User->login()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-10 06:44:20 --> Predis\Response\ServerException: ERR syntax error
[Method: GET, Route: login]
in VENDORPATH\predis\predis\src\Client.php on line 422.
 1 VENDORPATH\predis\predis\src\Client.php(387): Predis\Client->onErrorResponse(Object(Predis\Command\Redis\SET), Object(Predis\Response\Error))
 2 VENDORPATH\predis\predis\src\Client.php(336): Predis\Client->executeCommand(Object(Predis\Command\Redis\SET))
 3 APPPATH\Controllers\User.php(52): Predis\Client->__call('set', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\User->login()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
